version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Fody
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
  - dependency-name: Microsoft.NETCore.Platforms
    versions:
    - 5.0.0
    - 5.0.1
  - dependency-name: Microsoft.NETCore.UniversalWindowsPlatform
    versions:
    - 6.2.11
